name: Run PHP Script Once

on:
  workflow_dispatch:   # یعنی دستی اجرا می‌کنی

jobs:
  run-php:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Run PHP script
        run: php send.php